using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Durian.DefaultParam
{
	public static class DefaultParamMethodConfigurationAttribute
	{
		public static readonly string AttributeName = "DefaultParamMethodConfiguration";
		public static readonly string FullTypeName = DurianStrings.GetFullAttributeType(AttributeName);
		public static readonly string FullyQualifiedName = DurianStrings.GetFullyQualifiedConfigurationAttribute(AttributeName);
		public static readonly string CallInsteadOfCopyingProperty = "CallInsteadOfCopying";

		public static string GetText()
		{
			return
$@"{AutoGenerated.GetHeader(DefaultParamGenerator.GeneratorName, DefaultParamGenerator.Version)}
using System;
using System.CodeDom.Compiler;

namespace {DurianStrings.ConfigurationNamespace}
{{
	/// <summary>
	/// Configures how the <see cref=""{DefaultParamAttribute.FullTypeName}""/> behaves when applied to this method.
	/// </summary>
	[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
	public sealed class {FullTypeName} : Attribute
	{{
		/// <summary>
		/// Determines whether the generated method should call this method instead of copying its contents.
		/// </summary>
		public bool {CallInsteadOfCopyingProperty} {{ get; set; }}

		/// <summary>
		/// Initializes a new instance of the <see cref=""{FullTypeName}""/> class.
		/// </summary>
		public {FullTypeName}()
		{{
		}}
	}}
}}
";
		}

		public static SourceText CreateSourceText()
		{
			return SourceText.From(GetText(), Encoding.UTF8);
		}

		public static CSharpSyntaxTree CreateSyntaxTree()
		{
			return (CSharpSyntaxTree)CSharpSyntaxTree.ParseText(GetText(), encoding: Encoding.UTF8);
		}
	}
}
