using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Durian.DefaultParam
{
	/// <summary>
	/// Static class that contains all the metadata of the actual <c>DefaultParamConfigurationAttribute</c>.
	/// </summary>
	public static class DefaultParamConfigurationAttribute
	{
		/// <summary>
		/// Name of the <c>DefaultParamConfigurationAttribute</c> without the 'Attribute' suffix, i.e. 'DefaultParamConfiguration'.
		/// </summary>
		public static string AttributeName => "DefaultParamConfiguration";

		/// <summary>
		/// Full name of the <c>DefaultParamConfigurationAttribute</c>, i.e. 'DefaultParamConfigurationAttribute'.
		/// </summary>
		public static string FullTypeName => DurianStrings.GetFullAttributeType(AttributeName);

		/// <summary>
		/// Fully qualified name of the <c>DefaultParamConfigurationAttribute</c>, i.e. 'Durian.Configuration.DefaultParamConfigurationAttribute'.
		/// </summary>
		public static string FullyQualifiedName => DurianStrings.GetFullyQualifiedConfigurationAttribute(AttributeName);

		/// <summary>
		/// Name of the <c>DefaultParamConfigurationAttribute.AllowOverridingOfDefaultParamValues</c> property, i.e. 'AllowOverridingOfDefaultParamValues'.
		/// </summary>
		public static string AllowOverridingOfDefaultParamValuesProperty => "AllowOverridingOfDefaultParamValues";

		/// <summary>
		/// Name of the <c>DefaultParamConfigurationAttribute.AllowAddingDefaultParamToNewParameters</c> property, i.e. 'AllowAddingDefaultParamToNewParameters'.
		/// </summary>
		public static string AllowAddingDefaultParamToNewParametersProperty => "AllowAddingDefaultParamToNewParameters";

		/// <summary>
		/// Name of the <c>DefaultParamConfigurationAttribute.ApplyNewToGeneratedMembersWithEquivalentSignature</c> property, i.e. 'ApplyNewToGeneratedMembersWithEquivalentSignature'.
		/// </summary>
		public static string ApplyNewToGeneratedMembersWithEquivalentSignatureProperty => "ApplyNewToGeneratedMembersWithEquivalentSignature";

		/// <summary>
		/// Name of the <c>DefaultParamConfigurationAttribute.CallInsteadOfCopying</c> property, i.e. 'CallInsteadOfCopying'.
		/// </summary>
		public static string CallInsteadOfCopyingProperty => "CallInsteadOfCopying";

		/// <summary>
		/// Returns full source code of the <c>DefaultParamConfigurationAttribute</c>.
		/// </summary>
		public static string GetText()
		{
			return
$@"{AutoGenerated.GetHeader(DefaultParamGenerator.GeneratorName, DefaultParamGenerator.Version)}
using System;
using System.CodeDom.Compiler;
using {DurianStrings.GeneratorAttributesNamespace};

namespace {DurianStrings.ConfigurationNamespace}
{{
	/// <summary>
	/// Configures how the <see cref=""{DefaultParamAttribute.FullTypeName}""/> behaves in the current assembly.
	/// </summary>
	[AttributeUsage(AttributeTargets.Assembly, AllowMultiple = false, Inherited = false)]
	[GeneratedCode(""{DefaultParamGenerator.GeneratorName}"", ""{DefaultParamGenerator.Version}"")]
	[DurianGenerated]
	public sealed class {FullTypeName} : Attribute
	{{
		/// <summary>
		/// Determines whether the generated method should call this method instead of copying its contents. Defaults to <see langword=""false""/>.
		/// </summary>
		public bool {CallInsteadOfCopyingProperty} {{ get; set; }}

		/// <summary>
		/// Determines whether to allow to override values of <see cref=""{DefaultParamAttribute.FullTypeName}""/>s for virtual methods. Defaults to <see langword=""false""/>.
		/// </summary>
		/// <example>
		/// The following sample...
		/// <code>
		/// partial class Test
		/// {{
		///		public virtual void Method&lt;[{DefaultParamAttribute.AttributeName}(typeof(string)]T&gt;(T value)
		///		{{
		///		}}
		/// }}
		/// 
		/// partial class Derived : Test
		/// {{
		///		public override void Method&lt;[{DefaultParamAttribute.AttributeName}(typeof(int)]T&gt;(T value)
		///		{{
		///		}}
		/// }}
		/// </code>
		/// ...will produce the following code:
		/// <code>
		/// partial class Test
		/// {{
		///		public virtual void Method(string value)
		///		{{
		///		}}
		/// }}
		/// 
		/// partial class Derived : Test
		/// {{
		///		public override void Method(string value)
		///		{{
		///		}}
		///		
		///		public void Method(int value)
		///		{{
		///		}}
		/// }}
		/// </code>
		/// </example>
		public bool {AllowOverridingOfDefaultParamValuesProperty} {{ get; set; }}

		/// <summary>
		/// Determines whether to allow adding new <see cref=""{DefaultParamAttribute.FullTypeName}""/>s to type parameters that don't have the <see cref=""{DefaultParamAttribute.FullTypeName}""/> defined on the base method. Defaults to <see langword=""false""/>.
		/// </summary>
		/// <example>
		/// The following sample...
		/// <code>
		/// partial class Test
		/// {{
		///		public virtual void Method&lt;T, [{DefaultParamAttribute.AttributeName}(typeof(string))]U&gt;(T value, U obj)
		///		{{
		///		}}
		///	}}
		///
		///	partial class Derived : Test
		///	{{
		///		public override void Method&lt;[{DefaultParamAttribute.AttributeName}(typeof(int))]T, [{DefaultParamAttribute.AttributeName}(typeof(string))]U&gt;(T value, U obj)
		///		{{
		///		}}
		///	}}
		/// </code>
		/// ...will produce the following code:
		/// <code>
		/// partial class Test
		///	{{
		///		public virtual void Method&lt;T&gt;(T value, string obj)
		///		{{
		///		}}
		///	}}
		///
		///	partial class Derived
		///	{{
		///		public override void Method&lt;T&gt;(T value, string obj)
		///		{{
		///		}}
		///
		///		public void Method(int value, string obj)
		///		{{
		///		}}
		///	}}
		/// </code>
		/// </example>
		public bool {AllowAddingDefaultParamToNewParametersProperty} {{ get; set; }}

		/// <summary>
		/// Determines whether to apply the <see langwrod=""new""/> modifier to the generated member when possible instead of reporting an error. Defaults to <see langword=""false""/>.
		/// </summary>
		/// <example>
		/// The following sample...
		/// <code>
		/// partial class Test
		/// {{
		///		public virtual void Method&lt;[{DefaultParamAttribute.AttributeName}(typeof(string)]T&gt;(T value)
		///		{{
		///		}}
		///		
		///		public void Method(int value)
		///		{{
		///		}}
		/// }}
		/// 
		/// partial class Derived : Test
		/// {{
		///		public override void Method&lt;[{DefaultParamAttribute.AttributeName}(typeof(int)]T&gt;(T value)
		///		{{
		///		}}
		/// }}
		/// </code>
		/// ...will produce the following code:
		/// <code>
		/// partial class Test
		/// {{
		///		public virtual void Method(string value)
		///		{{
		///		}}
		/// }}
		/// 
		/// partial class Derived : Test
		/// {{
		///		public override void Method(string value)
		///		{{
		///		}}
		///		
		///		public new void Method(int value)
		///		{{
		///		}}
		/// }}
		/// </code>
		/// </example>
		public bool {ApplyNewToGeneratedMembersWithEquivalentSignatureProperty} {{ get; set; }}

		/// <summary>
		/// Initializes a new instance of the <see cref=""{FullTypeName}""/> class.
		/// </summary>
		public {FullTypeName}()
		{{
		}}
	}}
}}
";
		}

		/// <summary>
		/// Returns full source code of the <c>DefaultParamConfigurationAttribute</c> as an instance of <see cref="SourceText"/> with the <see cref="Encoding.UTF8"/> applied.
		/// </summary>
		public static SourceText CreateSourceText()
		{
			return SourceText.From(GetText(), Encoding.UTF8);
		}

		/// <summary>
		/// Returns full <see cref="CSharpSyntaxTree"/> of the <c>DefaultParamConfigurationAttribute</c>.
		/// </summary>
		/// <param name="parseOptions"><see cref="CSharpParseOptions"/> that should be used when parsing the source code returned by the <see cref="GetText"/> method.</param>
		/// <param name="cancellationToken"><see cref="CancellationToken"/> that specifies if the operation should be canceled.</param>
		public static CSharpSyntaxTree CreateSyntaxTree(CSharpParseOptions? parseOptions = null, CancellationToken cancellationToken = default)
		{
			return (CSharpSyntaxTree)CSharpSyntaxTree.ParseText(GetText(), encoding: Encoding.UTF8, options: parseOptions, cancellationToken: cancellationToken);
		}
	}
}
