using System;

namespace Durian.Generator
{
	/// <summary>
	/// Marks the target member as generated by a Durian source generator.
	/// </summary>
	[AttributeUsage(AttributeTargets.All, AllowMultiple = false, Inherited = false)]
	public sealed class DurianGeneratedAttribute : Attribute
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="DurianGeneratedAttribute"/> class.
		/// </summary>
		public DurianGeneratedAttribute()
		{
		}
	}
}
