//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DefaultParamGenerator class (version 1.0.0).
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

partial class Test
{
	[GeneratedCode("DefaultParamGenerator", "1.0.0")]
	void Method()
	{
		int value = default;
	}
}
