//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DefaultParamGenerator class (version 1.0.0).
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections;
using System.Collections.Generic;

partial class Test
{
	/// <inheritdoc cref="Test.Method{T, U}(U)"/>
	[GeneratedCode("DefaultParamGenerator", "1.0.0")]
	void Method<T>(IEnumerable value) where T : IEnumerable<IEnumerable>
	{
		IEnumerable v = default(IEnumerable);
		object obj = (IEnumerable)2;
		Type type = typeof(IEnumerable);
		List<IEnumerable> list = new List<IEnumerable>();
	}
}
