using System;
using System.Text;
using Microsoft.VisualBasic.CompilerServices;

namespace Durian.Generator
{
	/// <summary>
	/// Marks the target member as generated by a Durian source generator.
	/// </summary>
	[AttributeUsage(AttributeTargets.All, AllowMultiple = false, Inherited = false)]
	public sealed class DurianGeneratedAttribute : Attribute
	{
		/// <summary>
		/// Member this code was generated from.
		/// </summary>
		public string? Source { get; }

		/// <summary>
		/// Initializes a new instance of the <see cref="DurianGeneratedAttribute"/> class.
		/// </summary>
		public DurianGeneratedAttribute()
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="DurianGeneratedAttribute"/> class.
		/// </summary>
		/// <param name="source">Member this code was generated from.</param>
		public DurianGeneratedAttribute(string? source)
		{
			Source = source;
		}
	}
}
