using Xunit;

namespace Durian.Tests.AnalysisCore.AutoGenerated
{
	public sealed class GetAttribute
	{
		[Fact]
		public void IncludesFullyQualifiedName_When_IncludeFullyQualifiedNameIsTrue()
		{
			Assert.True(
				Durian.AutoGenerated.GetAttribute(GetHeader.GeneratorName, GetHeader.GeneratorVersion, true) ==
				$"[System.CodeDom.Compiler.GeneratedCode(\"{GetHeader.GeneratorName}\", \"{GetHeader.GeneratorVersion}\")]"
			);
		}

		[Fact]
		public void ExcludesFullyQualifiedName_When_IncludeFullyQualifiedNameIsFalse()
		{
			Assert.True(
				Durian.AutoGenerated.GetAttribute(GetHeader.GeneratorName, GetHeader.GeneratorVersion, false) ==
				$"[GeneratedCode(\"{GetHeader.GeneratorName}\", \"{GetHeader.GeneratorVersion}\")]"
			);
		}
	}
}
