using Xunit;

namespace Durian.Tests.AnalysisCore.AutoGenerated
{
	public sealed class GetInheritdoc
	{
		[Fact]
		public void ReturnsInheritDocWithNoCref_When_NoCrefSpecified()
		{
			Assert.True(Durian.AutoGenerated.GetInheritdoc() == "/// <inheritdoc/>");
		}

		[Fact]
		public void ReturnsInheritDocWithNoCref_When_NoCrefWasNull()
		{
			Assert.True(Durian.AutoGenerated.GetInheritdoc() == "/// <inheritdoc/>");
		}

		[Fact]
		public void ReturnsInheritDocWithCref_When_CrefWasSpecified()
		{
			const string input = "Test.Parent";
			Assert.True(Durian.AutoGenerated.GetInheritdoc(input) == $"/// <inheritdoc cref=\"{input}\"/>");
		}
	}
}
