namespace Durian.Generator
{
	/// <summary>
	/// Type of a syntax tree that was statically generated by a source generator.
	/// </summary>
	public enum StaticTreeType
	{
		/// <summary>
		/// Represents an <see cref="System.Attribute"/> type.
		/// </summary>
		Attribute,

		/// <summary>
		/// Represents an <see cref="System.Exception"/> type.
		/// </summary>
		Exception,

		/// <summary>
		/// Represents a <see cref="System.Delegate"/> type.
		/// </summary>
		Delegate,

		/// <summary>
		/// Represents a non-<see langword="static"/> <see langword="class"/>.
		/// </summary>
		Class,

		/// <summary>
		/// Represents a <see langword="static"/> <see langword="class"/>.
		/// </summary>
		StaticClass,

		/// <summary>
		/// Represents a <see langword="struct"/>.
		/// </summary>
		Struct,

		/// <summary>
		/// Represents an <see langword="interface"/>.
		/// </summary>
		Interface,

		/// <summary>
		/// Represents a set of configurations, such as assembly-scoped attributes.
		/// </summary>
		Configuration,

		/// <summary>
		/// Represents a generated syntax tree that does not fall into scope of any of the previous categories.
		/// </summary>
		Other
	}
}
