// Copyright (c) Piotr Stenke. All rights reserved.
// Licensed under the MIT license.

using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using Durian.Analysis.Cache;
using Durian.Analysis.Data;
using Durian.Analysis.Extensions;
using Durian.Analysis.Filters;
using Durian.Analysis.Logging;
using Durian.Info;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Durian.Analysis.CopyFrom
{
	/// <summary>
	/// Main class of the <c>CopyFrom</c> module. Generates source code of members marked with the <c>Durian.CopyFromAttribute</c>.
	/// </summary>
	[Generator(LanguageNames.CSharp)]
	[LoggingConfiguration(
		SupportedLogs = GeneratorLogs.All,
		LogDirectory = "CopyFrom",
		SupportsDiagnostics = true,
		RelativeToGlobal = true,
		EnableExceptions = true,
		DefaultNodeOutput = NodeOutput.SyntaxTree)]
	public sealed partial class CopyFromGenerator : CachedGenerator<ICopyFromMember>
	{
		private const int _numStaticTrees = 4;

		/// <inheritdoc/>
		public override string GeneratorName => "CopyFrom";

		/// <inheritdoc/>
		public override string GeneratorVersion => "1.0.0";

		/// <inheritdoc/>
		public override int NumStaticTrees => _numStaticTrees;

		/// <summary>
		/// Initializes a new instance of the <see cref="CopyFromGenerator"/> class.
		/// </summary>
		public CopyFromGenerator()
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CopyFromGenerator"/> class.
		/// </summary>
		/// <param name="context">Configures how this <see cref="CopyFromGenerator"/> is initialized.</param>
		public CopyFromGenerator(in GeneratorLogCreationContext context) : base(in context)
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="CopyFromGenerator"/> class.
		/// </summary>
		/// <param name="loggingConfiguration">Determines how the source generator should behave when logging information.</param>
		public CopyFromGenerator(LoggingConfiguration? loggingConfiguration) : base(loggingConfiguration)
		{
		}

		/// <summary>
		/// Returns a collection of <see cref="ISourceTextProvider"/> used by this generator to create initial sources.
		/// </summary>
		public static IEnumerable<ISourceTextProvider> GetSourceProviders()
		{
			return new ISourceTextProvider[_numStaticTrees - 1]
			{
				new CopyFromTypeAttributeProvider(),
				new CopyFromMethodAttributeProvider(),
				new PatternAttributeProvider(),
			};
		}

		/// <inheritdoc/>
		public override ICompilationData? CreateCompilationData(CSharpCompilation compilation)
		{
			return new CopyFromCompilationData(compilation);
		}

		/// <inheritdoc/>
		public override IDurianSyntaxReceiver CreateSyntaxReceiver()
		{
			return new CopyFromSyntaxReceiver();
		}

		/// <inheritdoc/>
		public override IReadOnlyFilterContainer<IGeneratorSyntaxFilter>? GetFilters(GeneratorPassBuilderContext context)
		{
			FilterContainer<IGeneratorSyntaxFilter> list = new();

			list.RegisterGroup("Methods", new Methods.CopyFromMethodFilter());
			list.RegisterGroup("Types", new Types.CopyFromTypeFilter());

			return list;
		}

		/// <inheritdoc/>
		public override IEnumerable<ISourceTextProvider>? GetInitialSources()
		{
			return GetSourceProviders();
		}

		/// <inheritdoc/>
		public override DurianModule[] GetRequiredModules()
		{
			return new DurianModule[]
			{
				DurianModule.CopyFrom
			};
		}

		/// <inheritdoc/>
		protected internal override bool Generate(IMemberData data, string hintName, GeneratorPassBuilderContext context)
		{
			if (data is not ICopyFromMember target)
			{
				return false;
			}

			if (target is Types.CopyFromTypeData type)
			{
				return GenerateType(type, hintName, context);
			}

			return false;
		}

		private static DocumentationCommentTriviaSyntax? GetDocumentationTrivia(CSharpSyntaxNode node)
		{
			return node
				.GetLeadingTrivia()
				.Where(trivia => trivia.HasStructure)
				.Select(trivia => trivia.GetStructure())
				.OfType<DocumentationCommentTriviaSyntax>()
				.FirstOrDefault();
		}

		private void WriteGeneratedMember(
			ICopyFromMember member,
			CSharpSyntaxNode node,
			ISymbol original,
			GeneratorPassBuilderContext context,
			GenerateDocumentation applyInheritdoc,
			DocumentationCommentTriviaSyntax? documentation
		)
		{
			string current = NodeToString(node);
			string generatedFrom = AutoGenerated.GetDurianGeneratedAttribute(SymbolToString(original));

			if(documentation is null)
			{
				for (int i = 0; i < member.Patterns!.Length; i++)
				{
					ref readonly PatternData pattern = ref member.Patterns[i];

					Regex regex = new(pattern.Pattern, RegexOptions.CultureInvariant | RegexOptions.Singleline);
					current = regex.Replace(current, pattern.Replacement);
				}

				if (applyInheritdoc == GenerateDocumentation.Always)
				{
					WriteGeneratedMember_Internal(current, generatedFrom, AutoGenerated.GetInheritdoc(original.GetXmlFullyQualifiedName()), context);
				}
				else
				{
					WriteGeneratedMember_Internal(current, generatedFrom, context);
				}

				return;
			}

			string doc = documentation.ToFullString();

			for (int i = 0; i < member.Patterns!.Length; i++)
			{
				ref readonly PatternData pattern = ref member.Patterns[i];

				Regex regex = new(pattern.Pattern, RegexOptions.CultureInvariant | RegexOptions.Singleline);
				current = regex.Replace(current, pattern.Replacement);
				doc = regex.Replace(doc, pattern.Replacement);
			}

			context.CodeBuilder.Indent();
			context.CodeBuilder.Write(doc);
			WriteGeneratedMember_Internal(current, generatedFrom, context);
		}

		private void WriteGeneratedMember(
			ICopyFromMember member,
			CSharpSyntaxNode node,
			ISymbol original,
			GeneratorPassBuilderContext context,
			GenerateDocumentation applyInheritdoc
		)
		{
			if (member.Patterns is null || member.Patterns.Length == 0)
			{
				WriteGeneratedMember(node, original, context, applyInheritdoc);
				return;
			}

			DocumentationCommentTriviaSyntax? documentation = default;

			if (applyInheritdoc != GenerateDocumentation.Never)
			{
				documentation = GetDocumentationTrivia(node);
			}

			WriteGeneratedMember(
				member,
				node,
				original,
				context,
				applyInheritdoc,
				documentation
			);
		}
	}
}
